/**
 * One-time setup script: creates the "Messi" Vapi assistant for the AI Mock
 * Interview via Vapi's REST API, and writes the resulting assistant id back
 * into backend/.env as VAPI_ASSISTANT_ID.
 *
 * Why this is a script you run locally instead of something Claude ran for
 * you: Claude's cloud sandbox can't reach api.vapi.ai (blocked by its own
 * egress policy), so this has to run from a machine that can reach the
 * public internet - yours.
 *
 * Usage (from the backend/ folder):
 *   node scripts/setupVapiAssistant.js
 *
 * Requires VAPI_PRIVATE_KEY to already be set in backend/.env (see
 * backend/.env.example). Safe to re-run - it always creates a new assistant
 * and overwrites VAPI_ASSISTANT_ID in .env with the latest one, so re-run
 * this if you ever change the assistant config in this file and want a
 * fresh assistant rather than editing the old one directly in the Vapi
 * dashboard.
 */
require("dotenv").config();
const fs = require("fs");
const path = require("path");
const axios = require("axios");

const VAPI_PRIVATE_KEY = process.env.VAPI_PRIVATE_KEY;
const ENV_PATH = path.join(__dirname, "..", ".env");

// Defaults to the deployed backend; override with VAPI_LLM_URL if you're
// testing against a tunnel (e.g. ngrok) pointed at your local dev server -
// Vapi's servers call this URL directly, so it must be publicly reachable
// over HTTPS (localhost will NOT work).
const LLM_URL = process.env.VAPI_LLM_URL || "https://talentera-1.onrender.com/api/vapi/llm";

// The exact phrase Messi says to end the interview - must stay identical to
// CLOSING_PHRASE in backend/routes/vapiInterview.js, or Vapi won't recognize
// it and the call will just hang open after the final question.
const CLOSING_PHRASE = "This concludes your AI Mock Interview";

async function main() {
  if (!VAPI_PRIVATE_KEY) {
    console.error(
      "VAPI_PRIVATE_KEY is not set in backend/.env - add it (from your Vapi Dashboard -> API Keys) and re-run this script."
    );
    process.exit(1);
  }

  console.log(`Creating Vapi assistant, Custom LLM pointed at: ${LLM_URL}`);

  const payload = {
    name: "Messi - Talentera AI Mock Interviewer",
    // The opening line is personalized per-candidate (name, role) by our own
    // Custom LLM, not a static string - so Vapi should call the model for
    // the very first line too, instead of speaking a canned firstMessage.
    firstMessageMode: "assistant-speaks-first-with-model-generated-message",
    model: {
      provider: "custom-llm",
      // Vapi requires a model name even in Custom LLM mode (it's passed
      // through in the request body Vapi sends to our webhook) - this must
      // match the "model" field routes/vapiInterview.js returns in its
      // OpenAI-shaped response (openAiChunk's `model: "messi-talentera"`).
      model: "messi-talentera",
      url: LLM_URL,
      messages: [
        {
          role: "system",
          // {{authToken}} is substituted by Vapi from the variableValues the
          // frontend passes into vapi.start() (see ClaudeMockInterviewBot.jsx)
          // - our /api/vapi/llm route extracts it from this exact system
          // message to identify which candidate the call belongs to.
          content:
            "You are Messi, Talentera's AI technical interviewer. All of your actual replies are generated by the connected custom LLM server - just relay what it returns verbatim, do not add anything of your own. [AUTH_TOKEN:{{authToken}}]",
        },
      ],
    },
    voice: {
      provider: "11labs",
      model: "eleven_flash_v2_5",
      voiceId: "sarah",
    },
    endCallPhrases: [CLOSING_PHRASE],
    silenceTimeoutSeconds: 30,
    maxDurationSeconds: 1200,
  };

  let response;
  try {
    response = await axios.post("https://api.vapi.ai/assistant", payload, {
      headers: {
        Authorization: `Bearer ${VAPI_PRIVATE_KEY}`,
        "Content-Type": "application/json",
      },
      timeout: 20000,
    });
  } catch (err) {
    console.error("Failed to create Vapi assistant:");
    console.error(err.response?.data || err.message);
    process.exit(1);
  }

  const assistantId = response.data?.id;
  if (!assistantId) {
    console.error("Vapi did not return an assistant id. Raw response:", response.data);
    process.exit(1);
  }

  console.log(`Assistant created: ${assistantId}`);

  // Write/update VAPI_ASSISTANT_ID in backend/.env so the frontend build
  // (via a matching VITE_VAPI_ASSISTANT_ID you'll also need to set - printed
  // below) and any backend code that needs it can read it without you
  // copy-pasting by hand.
  let envContent = "";
  try {
    envContent = fs.readFileSync(ENV_PATH, "utf8");
  } catch (e) {
    console.warn(`Could not read ${ENV_PATH} - printing the id instead of writing it: ${assistantId}`);
    return;
  }

  const line = `VAPI_ASSISTANT_ID=${assistantId}`;
  if (/^VAPI_ASSISTANT_ID=.*$/m.test(envContent)) {
    envContent = envContent.replace(/^VAPI_ASSISTANT_ID=.*$/m, line);
  } else {
    envContent = envContent.trimEnd() + `\n${line}\n`;
  }
  fs.writeFileSync(ENV_PATH, envContent, "utf8");
  console.log(`Wrote VAPI_ASSISTANT_ID to ${ENV_PATH}`);
  console.log("\nNext step: add the SAME id to frontend/.env as:");
  console.log(`VITE_VAPI_ASSISTANT_ID=${assistantId}`);
  console.log(`VITE_VAPI_PUBLIC_KEY=<your Vapi Public Key>`);
}

main();
