const fs = require('fs');

let s = fs.readFileSync('frontend/src/pages/StaffHub.jsx', 'utf8').replace(/\r\n/g, '\n');
s = s.replace(/<div style=\{\{ fontSize: 22,[\s\S]*?>\s*🎯\s*<\/div>/g, '<div style={{ fontSize: 18, flexShrink: 0, boxShadow: "0 4px 10px rgba(37,99,235,0.25)" }}><i className="fa-solid fa-bullseye"></i></div>');
s = s.replace(/<div style=\{\{ fontSize: 20,[\s\S]*?>\s*🎤\s*<\/div>/g, '<div style={{ fontSize: 18, flexShrink: 0, boxShadow: "0 4px 10px rgba(5,150,105,0.25)" }}><i className="fa-solid fa-microphone"></i></div>');
s = s.replace(/<span style=\{\{ position: "absolute", left: 11, top: "50%", transform: "translateY\(-50%\)", color: "#94A3B8", fontSize: 13 \}\}>\s*🔍\s*<\/span>/g, '<span style={{ position: "absolute", left: 11, top: "50%", transform: "translateY(-50%)", color: "#94A3B8", fontSize: 13 }}><i className="fa-solid fa-magnifying-glass"></i></span>');
s = s.replace(/<div style=\{\{ width: 48, height: 48, borderRadius: 14, background: "rgba\(255,255,255,0.1\)", color: "var\(--gold, #E5A82E\)", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 20, fontWeight: 800 \}\}>\s*🏢\s*<\/div>/g, '<div style={{ width: 48, height: 48, borderRadius: 14, background: "rgba(255,255,255,0.1)", color: "var(--gold, #E5A82E)", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 20, fontWeight: 800 }}><i className="fa-solid fa-building"></i></div>');
s = s.replace(/<div style=\{\{ width: 48, height: 48, borderRadius: 14, background: "rgba\(255,255,255,0.1\)", color: "var\(--gold, #E5A82E\)", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 20, fontWeight: 800 \}\}>\s*🎓\s*<\/div>/g, '<div style={{ width: 48, height: 48, borderRadius: 14, background: "rgba(255,255,255,0.1)", color: "var(--gold, #E5A82E)", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 20, fontWeight: 800 }}><i className="fa-solid fa-graduation-cap"></i></div>');
fs.writeFileSync('frontend/src/pages/StaffHub.jsx', s, 'utf8');

let cp = fs.readFileSync('frontend/src/pages/CompanyPortal.jsx', 'utf8').replace(/\r\n/g, '\n');
cp = cp.replace(/<div style=\{\{ width: 44, height: 44, borderRadius: "50%", background: "#DCFCE7", color: "#15803D", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 20 \}\}>\s*📞\s*<\/div>/g, '<div style={{ width: 44, height: 44, borderRadius: "50%", background: "#DCFCE7", color: "#15803D", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 18 }}><i className="fa-solid fa-phone"></i></div>');
cp = cp.replace(/<div style=\{\{ width: 56, height: 56, borderRadius: "50%", background: "#FEF3C7", color: "#D97706", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 28, margin: "0 auto 16px" \}\}>\s*🔒\s*<\/div>/g, '<div style={{ width: 56, height: 56, borderRadius: "50%", background: "#FEF3C7", color: "#D97706", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 24, margin: "0 auto 16px" }}><i className="fa-solid fa-lock"></i></div>');
cp = cp.replace(/<div style=\{\{ width: 56, height: 56, borderRadius: "50%", background: "#EFF6FF", color: "#2563EB", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 28, margin: "0 auto 16px" \}\}>\s*⚡\s*<\/div>/g, '<div style={{ width: 56, height: 56, borderRadius: "50%", background: "#EFF6FF", color: "#2563EB", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 24, margin: "0 auto 16px" }}><i className="fa-solid fa-bolt"></i></div>');
fs.writeFileSync('frontend/src/pages/CompanyPortal.jsx', cp, 'utf8');

console.log('clean_exact completed.');
